CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  username VARCHAR(25) NOT NULL,
  password VARCHAR(250) NOT NULL,
  email VARCHAR(75) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP 
);
  
CREATE TABLE posts(
  user_id INT NOT NULL,
  id SERIAL PRIMARY KEY NOT NULL,
  body VARCHAR(140) NOT NULL,
	username VARCHAR(25) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP, 
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
);
  
CREATE TABLE post_likes(
  user_id INT NOT NULL,
  post_id INT NOT NULL,
	username VARCHAR(25),
  id SERIAL PRIMARY KEY NOT NULL,
  reaction VARCHAR(140) DEFAULT 'like',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP, 
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY(post_id) REFERENCES posts(id) ON DELETE CASCADE
);
	   
CREATE TABLE post_comments(
 	user_id INT NOT NULL,
 	post_id INT NOT NULL,
  id SERIAL PRIMARY KEY NOT NULL,
  body VARCHAR(140) NOT NULL,
	username VARCHAR(25),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP, 
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY(post_id) REFERENCES posts(id) ON DELETE CASCADE
 );

 CREATE TABLE comments_likes(
  user_id INT NOT NULL,
  comment_id INT NOT NULL,
	username VARCHAR(25),
  id SERIAL PRIMARY KEY NOT NULL,
  reaction VARCHAR(140) DEFAULT 'like',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP, 
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY(comment_id) REFERENCES post_comments(id) ON DELETE CASCADE
);